//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ReferenciaServicios.WRGestionProductos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGestionProductosSoap", Namespace="http://tempuri.org/")]
    public partial class WSGestionProductos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGestionProductos() {
            this.Url = global::ReferenciaServicios.Properties.Settings.Default.ReferenciaServicios_WRGestionProductos_WSGestionProductos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarProductosCompletedEventHandler ListarProductosCompleted;
        
        /// <remarks/>
        public event CrearProductoCompletedEventHandler CrearProductoCompleted;
        
        /// <remarks/>
        public event ActualizarProductoCompletedEventHandler ActualizarProductoCompleted;
        
        /// <remarks/>
        public event EliminarProductoCompletedEventHandler EliminarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductosRPT ListarProductos() {
            object[] results = this.Invoke("ListarProductos", new object[0]);
            return ((ProductosRPT)(results[0]));
        }
        
        /// <remarks/>
        public void ListarProductosAsync() {
            this.ListarProductosAsync(null);
        }
        
        /// <remarks/>
        public void ListarProductosAsync(object userState) {
            if ((this.ListarProductosOperationCompleted == null)) {
                this.ListarProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProductosOperationCompleted);
            }
            this.InvokeAsync("ListarProductos", new object[0], this.ListarProductosOperationCompleted, userState);
        }
        
        private void OnListarProductosOperationCompleted(object arg) {
            if ((this.ListarProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProductosCompleted(this, new ListarProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CrearProducto(ProductCreateDto dtoProducto) {
            object[] results = this.Invoke("CrearProducto", new object[] {
                        dtoProducto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearProductoAsync(ProductCreateDto dtoProducto) {
            this.CrearProductoAsync(dtoProducto, null);
        }
        
        /// <remarks/>
        public void CrearProductoAsync(ProductCreateDto dtoProducto, object userState) {
            if ((this.CrearProductoOperationCompleted == null)) {
                this.CrearProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearProductoOperationCompleted);
            }
            this.InvokeAsync("CrearProducto", new object[] {
                        dtoProducto}, this.CrearProductoOperationCompleted, userState);
        }
        
        private void OnCrearProductoOperationCompleted(object arg) {
            if ((this.CrearProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearProductoCompleted(this, new CrearProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizarProducto(ProductUpdateDto dtoProducto) {
            object[] results = this.Invoke("ActualizarProducto", new object[] {
                        dtoProducto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarProductoAsync(ProductUpdateDto dtoProducto) {
            this.ActualizarProductoAsync(dtoProducto, null);
        }
        
        /// <remarks/>
        public void ActualizarProductoAsync(ProductUpdateDto dtoProducto, object userState) {
            if ((this.ActualizarProductoOperationCompleted == null)) {
                this.ActualizarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarProductoOperationCompleted);
            }
            this.InvokeAsync("ActualizarProducto", new object[] {
                        dtoProducto}, this.ActualizarProductoOperationCompleted, userState);
        }
        
        private void OnActualizarProductoOperationCompleted(object arg) {
            if ((this.ActualizarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarProductoCompleted(this, new ActualizarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminarProducto(int idProducto) {
            object[] results = this.Invoke("EliminarProducto", new object[] {
                        idProducto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(int idProducto) {
            this.EliminarProductoAsync(idProducto, null);
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(int idProducto, object userState) {
            if ((this.EliminarProductoOperationCompleted == null)) {
                this.EliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("EliminarProducto", new object[] {
                        idProducto}, this.EliminarProductoOperationCompleted, userState);
        }
        
        private void OnEliminarProductoOperationCompleted(object arg) {
            if ((this.EliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarProductoCompleted(this, new EliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductosRPT {
        
        private ProductoCN[] paProductosField;
        
        /// <remarks/>
        public ProductoCN[] paProductos {
            get {
                return this.paProductosField;
            }
            set {
                this.paProductosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoCN {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductUpdateDto {
        
        private int nIdeProField;
        
        private string cNomProField;
        
        private string cDesProField;
        
        private decimal nPreProField;
        
        private int nStoProField;
        
        /// <remarks/>
        public int nIdePro {
            get {
                return this.nIdeProField;
            }
            set {
                this.nIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string cNomPro {
            get {
                return this.cNomProField;
            }
            set {
                this.cNomProField = value;
            }
        }
        
        /// <remarks/>
        public string cDesPro {
            get {
                return this.cDesProField;
            }
            set {
                this.cDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal nPrePro {
            get {
                return this.nPreProField;
            }
            set {
                this.nPreProField = value;
            }
        }
        
        /// <remarks/>
        public int nStoPro {
            get {
                return this.nStoProField;
            }
            set {
                this.nStoProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductCreateDto {
        
        private string cNomProField;
        
        private string cDesProField;
        
        private decimal nPreProField;
        
        private int nStoProField;
        
        /// <remarks/>
        public string cNomPro {
            get {
                return this.cNomProField;
            }
            set {
                this.cNomProField = value;
            }
        }
        
        /// <remarks/>
        public string cDesPro {
            get {
                return this.cDesProField;
            }
            set {
                this.cDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal nPrePro {
            get {
                return this.nPreProField;
            }
            set {
                this.nPreProField = value;
            }
        }
        
        /// <remarks/>
        public int nStoPro {
            get {
                return this.nStoProField;
            }
            set {
                this.nStoProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ListarProductosCompletedEventHandler(object sender, ListarProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductosRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductosRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CrearProductoCompletedEventHandler(object sender, CrearProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ActualizarProductoCompletedEventHandler(object sender, ActualizarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void EliminarProductoCompletedEventHandler(object sender, EliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591