//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ReferenciaServicios.WRGestionProductos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGestionProductosSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
    public partial class WSGestionProductos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wmObtenerProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmCrearProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmActualizarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmEliminarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGestionProductos() {
            this.Url = global::ReferenciaServicios.Properties.Settings.Default.ReferenciaServicios_WRGestionProductos_WSGestionProductos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wmObtenerProductosCompletedEventHandler wmObtenerProductosCompleted;
        
        /// <remarks/>
        public event wmCrearProductoCompletedEventHandler wmCrearProductoCompleted;
        
        /// <remarks/>
        public event wmActualizarProductoCompletedEventHandler wmActualizarProductoCompleted;
        
        /// <remarks/>
        public event wmEliminarProductoCompletedEventHandler wmEliminarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmObtenerProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductosListRPT wmObtenerProductos() {
            object[] results = this.Invoke("wmObtenerProductos", new object[0]);
            return ((ProductosListRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmObtenerProductosAsync() {
            this.wmObtenerProductosAsync(null);
        }
        
        /// <remarks/>
        public void wmObtenerProductosAsync(object userState) {
            if ((this.wmObtenerProductosOperationCompleted == null)) {
                this.wmObtenerProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmObtenerProductosOperationCompleted);
            }
            this.InvokeAsync("wmObtenerProductos", new object[0], this.wmObtenerProductosOperationCompleted, userState);
        }
        
        private void OnwmObtenerProductosOperationCompleted(object arg) {
            if ((this.wmObtenerProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmObtenerProductosCompleted(this, new wmObtenerProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmCrearProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoCrearRPT wmCrearProducto(ProductoCrearRQT toCrePro) {
            object[] results = this.Invoke("wmCrearProducto", new object[] {
                        toCrePro});
            return ((ProductoCrearRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmCrearProductoAsync(ProductoCrearRQT toCrePro) {
            this.wmCrearProductoAsync(toCrePro, null);
        }
        
        /// <remarks/>
        public void wmCrearProductoAsync(ProductoCrearRQT toCrePro, object userState) {
            if ((this.wmCrearProductoOperationCompleted == null)) {
                this.wmCrearProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmCrearProductoOperationCompleted);
            }
            this.InvokeAsync("wmCrearProducto", new object[] {
                        toCrePro}, this.wmCrearProductoOperationCompleted, userState);
        }
        
        private void OnwmCrearProductoOperationCompleted(object arg) {
            if ((this.wmCrearProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmCrearProductoCompleted(this, new wmCrearProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmActualizarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoActualizarRPT wmActualizarProducto(ProductoActualizarRQT toActPro) {
            object[] results = this.Invoke("wmActualizarProducto", new object[] {
                        toActPro});
            return ((ProductoActualizarRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmActualizarProductoAsync(ProductoActualizarRQT toActPro) {
            this.wmActualizarProductoAsync(toActPro, null);
        }
        
        /// <remarks/>
        public void wmActualizarProductoAsync(ProductoActualizarRQT toActPro, object userState) {
            if ((this.wmActualizarProductoOperationCompleted == null)) {
                this.wmActualizarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmActualizarProductoOperationCompleted);
            }
            this.InvokeAsync("wmActualizarProducto", new object[] {
                        toActPro}, this.wmActualizarProductoOperationCompleted, userState);
        }
        
        private void OnwmActualizarProductoOperationCompleted(object arg) {
            if ((this.wmActualizarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmActualizarProductoCompleted(this, new wmActualizarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmEliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoEliminarRPT wmEliminarProducto(ProductoEliminarRQT toEliPro) {
            object[] results = this.Invoke("wmEliminarProducto", new object[] {
                        toEliPro});
            return ((ProductoEliminarRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmEliminarProductoAsync(ProductoEliminarRQT toEliPro) {
            this.wmEliminarProductoAsync(toEliPro, null);
        }
        
        /// <remarks/>
        public void wmEliminarProductoAsync(ProductoEliminarRQT toEliPro, object userState) {
            if ((this.wmEliminarProductoOperationCompleted == null)) {
                this.wmEliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("wmEliminarProducto", new object[] {
                        toEliPro}, this.wmEliminarProductoOperationCompleted, userState);
        }
        
        private void OnwmEliminarProductoOperationCompleted(object arg) {
            if ((this.wmEliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmEliminarProductoCompleted(this, new wmEliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductosListRPT : Error {
        
        private ProductoListaCN[] paProductosField;
        
        /// <remarks/>
        public ProductoListaCN[] paProductos {
            get {
                return this.paProductosField;
            }
            set {
                this.paProductosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoListaCN {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoEliminarRQT {
        
        private int pnIdeProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoActualizarRQT {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoCrearRQT {
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoEliminarRPT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoActualizarRPT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoCrearRPT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductosListRPT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoEliminarRPT : Error {
        
        private int pnIdeProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoActualizarRPT : Error {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoCrearRPT : Error {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void wmObtenerProductosCompletedEventHandler(object sender, wmObtenerProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmObtenerProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmObtenerProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductosListRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductosListRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void wmCrearProductoCompletedEventHandler(object sender, wmCrearProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmCrearProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmCrearProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoCrearRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoCrearRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void wmActualizarProductoCompletedEventHandler(object sender, wmActualizarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmActualizarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmActualizarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoActualizarRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoActualizarRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void wmEliminarProductoCompletedEventHandler(object sender, wmEliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmEliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmEliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoEliminarRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoEliminarRPT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591