//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ReferenciaServicios.WRGestionProductos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGestionProductosSoap", Namespace="http://tempuri.org/")]
    public partial class WSGestionProductos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mxObtenerProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback mxCrearProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mxActualizarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mxEliminarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGestionProductos() {
            this.Url = global::ReferenciaServicios.Properties.Settings.Default.ReferenciaServicios_WRGestionProductos_WSGestionProductos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mxObtenerProductosCompletedEventHandler mxObtenerProductosCompleted;
        
        /// <remarks/>
        public event mxCrearProductoCompletedEventHandler mxCrearProductoCompleted;
        
        /// <remarks/>
        public event mxActualizarProductoCompletedEventHandler mxActualizarProductoCompleted;
        
        /// <remarks/>
        public event mxEliminarProductoCompletedEventHandler mxEliminarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mxObtenerProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductosListRPT mxObtenerProductos() {
            object[] results = this.Invoke("mxObtenerProductos", new object[0]);
            return ((ProductosListRPT)(results[0]));
        }
        
        /// <remarks/>
        public void mxObtenerProductosAsync() {
            this.mxObtenerProductosAsync(null);
        }
        
        /// <remarks/>
        public void mxObtenerProductosAsync(object userState) {
            if ((this.mxObtenerProductosOperationCompleted == null)) {
                this.mxObtenerProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmxObtenerProductosOperationCompleted);
            }
            this.InvokeAsync("mxObtenerProductos", new object[0], this.mxObtenerProductosOperationCompleted, userState);
        }
        
        private void OnmxObtenerProductosOperationCompleted(object arg) {
            if ((this.mxObtenerProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mxObtenerProductosCompleted(this, new mxObtenerProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mxCrearProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoCrearRPT mxCrearProducto(ProductoCrearRQT requestProducto) {
            object[] results = this.Invoke("mxCrearProducto", new object[] {
                        requestProducto});
            return ((ProductoCrearRPT)(results[0]));
        }
        
        /// <remarks/>
        public void mxCrearProductoAsync(ProductoCrearRQT requestProducto) {
            this.mxCrearProductoAsync(requestProducto, null);
        }
        
        /// <remarks/>
        public void mxCrearProductoAsync(ProductoCrearRQT requestProducto, object userState) {
            if ((this.mxCrearProductoOperationCompleted == null)) {
                this.mxCrearProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmxCrearProductoOperationCompleted);
            }
            this.InvokeAsync("mxCrearProducto", new object[] {
                        requestProducto}, this.mxCrearProductoOperationCompleted, userState);
        }
        
        private void OnmxCrearProductoOperationCompleted(object arg) {
            if ((this.mxCrearProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mxCrearProductoCompleted(this, new mxCrearProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mxActualizarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoActualizarRPT mxActualizarProducto(ProductoActualizarRQT requestProducto) {
            object[] results = this.Invoke("mxActualizarProducto", new object[] {
                        requestProducto});
            return ((ProductoActualizarRPT)(results[0]));
        }
        
        /// <remarks/>
        public void mxActualizarProductoAsync(ProductoActualizarRQT requestProducto) {
            this.mxActualizarProductoAsync(requestProducto, null);
        }
        
        /// <remarks/>
        public void mxActualizarProductoAsync(ProductoActualizarRQT requestProducto, object userState) {
            if ((this.mxActualizarProductoOperationCompleted == null)) {
                this.mxActualizarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmxActualizarProductoOperationCompleted);
            }
            this.InvokeAsync("mxActualizarProducto", new object[] {
                        requestProducto}, this.mxActualizarProductoOperationCompleted, userState);
        }
        
        private void OnmxActualizarProductoOperationCompleted(object arg) {
            if ((this.mxActualizarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mxActualizarProductoCompleted(this, new mxActualizarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mxEliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int mxEliminarProducto(int tnIdePro) {
            object[] results = this.Invoke("mxEliminarProducto", new object[] {
                        tnIdePro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void mxEliminarProductoAsync(int tnIdePro) {
            this.mxEliminarProductoAsync(tnIdePro, null);
        }
        
        /// <remarks/>
        public void mxEliminarProductoAsync(int tnIdePro, object userState) {
            if ((this.mxEliminarProductoOperationCompleted == null)) {
                this.mxEliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmxEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("mxEliminarProducto", new object[] {
                        tnIdePro}, this.mxEliminarProductoOperationCompleted, userState);
        }
        
        private void OnmxEliminarProductoOperationCompleted(object arg) {
            if ((this.mxEliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mxEliminarProductoCompleted(this, new mxEliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductosListRPT {
        
        private ProductoListaCN[] paProductosField;
        
        /// <remarks/>
        public ProductoListaCN[] paProductos {
            get {
                return this.paProductosField;
            }
            set {
                this.paProductosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoListaCN {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoActualizarRPT {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoActualizarRQT {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoCrearRPT {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoCrearRQT {
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void mxObtenerProductosCompletedEventHandler(object sender, mxObtenerProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mxObtenerProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mxObtenerProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductosListRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductosListRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void mxCrearProductoCompletedEventHandler(object sender, mxCrearProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mxCrearProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mxCrearProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoCrearRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoCrearRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void mxActualizarProductoCompletedEventHandler(object sender, mxActualizarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mxActualizarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mxActualizarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoActualizarRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoActualizarRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void mxEliminarProductoCompletedEventHandler(object sender, mxEliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mxEliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mxEliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591